### Player ###
player = "/usr/bin/mpv"

### Video Downloader ###
# You should be change the value of "bin" to your downloader executable file path.
[mpv]
bin = "/usr/bin/mpv"
cookies = "--ytdl-raw-options-append=cookies="
cookies_prefix = true
direct = true
quality.best = "--ytdl-format=bestvideo+bestaudio/best"
quality.360p = "--ytdl-format=bestvideo[height<=360]+bestaudio/best[height<=360]/best"
quality.480p = "--ytdl-format=bestvideo[height<=480]+bestaudio/best[height<=480]/best"
quality.720p = "--ytdl-format=bestvideo[height<=720]+bestaudio/best[height<=720]/best"
quality.1080p = "--ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]/best"
quality.1440p = "--ytdl-format=bestvideo[height<=1440]+bestaudio/best[height<=1440]/best"
quality.2160p = "--ytdl-format=bestvideo[height<=2160]+bestaudio/best[height<=2160]/best"

[ytdl]
bin = "/usr/bin/youtube-dl"
cookies = "--cookies"
pipeline = true
options = ["--quiet", "--output", "-"]

[you-get]
bin = "/usr/bin/you-get"
cookies = "--cookies"
options = ["--player"]

[streamlink]
bin = "/usr/bin/streamlink"
options = ["--player"]

# # For advanced user, you can add downloader manually.
# # Example:
#
# [example]
# bin = "/usr/bin/example"
# cookies = "--cookies"
# cookies_prefix = false
# direct = false
# pipeline = false
# options = ["--player"]
# quality.best = "--quality=best"
#
#
# [example]       Required, Type: String
#                   The value "example" is downloader table name
# bin             Required, Type: String
#                   The downloader executable binary path.
# cookies         Optional, Type: String (default: "")
#                   The downloader parameter of passthorgh cookies.
# cookies_prefix  Optional, Type: Boolen (default: false)
#                   Set as true to mark cookies parameter as prefix.
# direct          Optional, Type: Boolen (defalut: false)
#                   Set as true to mark downloader run directly without player.
# pipeline        Optional, Type: Boolen (default: false)
#                   Set as true to mark downloader transfer video data through pipeline.
# options         Optional, Type: Array of Strings (default: [])
#                   The parameters of downloader to set player or output.
# quality.LEVEL   Optional, Type: String
#                   The LEVEL is a key name
#                   The value is parameter of downloader to choose quality/format.
